### ISSUE TITLE
`static-params/strict` fails to import under unpkg/jsdelivr

### ISSUE THREAD

**Issue by Ristovski** [WebReflection/ube#1]
Seems like https://github.com/WebReflection/ube/commit/35b021cc0f173902280c3aa6c7b4884871856125 breaks ESM? No idea if this is "supported" since its using jsdelivr but:

```js
<script type="module">
    (async function () {
        let ube = await import('https://cdn.jsdelivr.net/npm/ube/+esm');
    })();
</script>
```

eventually tries importing `https://cdn.jsdelivr.net/npm/static-params@0.2.1/strict/+esm` which does not exist, but `https://cdn.jsdelivr.net/npm/static-params@0.2.1/+esm` does.

**Edit**: Same happens when trying the live example at https://codepen.io/WebReflection/pen/gOmaXrZ?editors=0010

**Comment by WebReflection** [comment]
both unpkg and jsdelivr don't seem to support standard NodeJS modules resolution, [defined in here](https://github.com/WebReflection/static-params/blob/master/package.json#L41-L44).

Skypack Dev works though, as expected, so I've updated the Pen

```js
import {HTML, render, html} from '//cdn.skypack.dev/ube';
```

**Comment by WebReflection** [comment]
P.S. alternatively you can use:

```js
import 'https://cdn.jsdelivr.net/npm/ube/es.js';

const {HTML, render, html} = ube;
```
